package api

// Code generated by github.com/tinylib/msgp DO NOT EDIT.

import (
	"github.com/tinylib/msgp/msgp"
)

// DecodeMsg implements msgp.Decodable
func (z *CertutilPkcs8DecryptParams) DecodeMsg(dc *msgp.Reader) (err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, err = dc.ReadMapHeader()
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, err = dc.ReadMapKeyPtr()
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "input":
			z.Input, err = dc.ReadBytes(z.Input)
			if err != nil {
				err = msgp.WrapError(err, "Input")
				return
			}
		case "password":
			z.Password, err = dc.ReadBytes(z.Password)
			if err != nil {
				err = msgp.WrapError(err, "Password")
				return
			}
		default:
			err = dc.Skip()
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	return
}

// EncodeMsg implements msgp.Encodable
func (z *CertutilPkcs8DecryptParams) EncodeMsg(en *msgp.Writer) (err error) {
	// map header, size 2
	// write "input"
	err = en.Append(0x82, 0xa5, 0x69, 0x6e, 0x70, 0x75, 0x74)
	if err != nil {
		return
	}
	err = en.WriteBytes(z.Input)
	if err != nil {
		err = msgp.WrapError(err, "Input")
		return
	}
	// write "password"
	err = en.Append(0xa8, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64)
	if err != nil {
		return
	}
	err = en.WriteBytes(z.Password)
	if err != nil {
		err = msgp.WrapError(err, "Password")
		return
	}
	return
}

// MarshalMsg implements msgp.Marshaler
func (z *CertutilPkcs8DecryptParams) MarshalMsg(b []byte) (o []byte, err error) {
	o = msgp.Require(b, z.Msgsize())
	// map header, size 2
	// string "input"
	o = append(o, 0x82, 0xa5, 0x69, 0x6e, 0x70, 0x75, 0x74)
	o = msgp.AppendBytes(o, z.Input)
	// string "password"
	o = append(o, 0xa8, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64)
	o = msgp.AppendBytes(o, z.Password)
	return
}

// UnmarshalMsg implements msgp.Unmarshaler
func (z *CertutilPkcs8DecryptParams) UnmarshalMsg(bts []byte) (o []byte, err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, bts, err = msgp.ReadMapHeaderBytes(bts)
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, bts, err = msgp.ReadMapKeyZC(bts)
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "input":
			z.Input, bts, err = msgp.ReadBytesBytes(bts, z.Input)
			if err != nil {
				err = msgp.WrapError(err, "Input")
				return
			}
		case "password":
			z.Password, bts, err = msgp.ReadBytesBytes(bts, z.Password)
			if err != nil {
				err = msgp.WrapError(err, "Password")
				return
			}
		default:
			bts, err = msgp.Skip(bts)
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	o = bts
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z *CertutilPkcs8DecryptParams) Msgsize() (s int) {
	s = 1 + 6 + msgp.BytesPrefixSize + len(z.Input) + 9 + msgp.BytesPrefixSize + len(z.Password)
	return
}
