package api

// Code generated by github.com/tinylib/msgp DO NOT EDIT.

import (
	"github.com/tinylib/msgp/msgp"
)

// DecodeMsg implements msgp.Decodable
func (z *VidMsgParams) DecodeMsg(dc *msgp.Reader) (err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, err = dc.ReadMapHeader()
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, err = dc.ReadMapKeyPtr()
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "input":
			z.Input, err = dc.ReadString()
			if err != nil {
				err = msgp.WrapError(err, "Input")
				return
			}
		case "serverCert":
			z.ServerCert, err = dc.ReadBytes(z.ServerCert)
			if err != nil {
				err = msgp.WrapError(err, "ServerCert")
				return
			}
		case "npkiRandomNum":
			z.NpkiRandomNum, err = dc.ReadBytes(z.NpkiRandomNum)
			if err != nil {
				err = msgp.WrapError(err, "NpkiRandomNum")
				return
			}
		default:
			err = dc.Skip()
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	return
}

// EncodeMsg implements msgp.Encodable
func (z *VidMsgParams) EncodeMsg(en *msgp.Writer) (err error) {
	// map header, size 3
	// write "input"
	err = en.Append(0x83, 0xa5, 0x69, 0x6e, 0x70, 0x75, 0x74)
	if err != nil {
		return
	}
	err = en.WriteString(z.Input)
	if err != nil {
		err = msgp.WrapError(err, "Input")
		return
	}
	// write "serverCert"
	err = en.Append(0xaa, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x43, 0x65, 0x72, 0x74)
	if err != nil {
		return
	}
	err = en.WriteBytes(z.ServerCert)
	if err != nil {
		err = msgp.WrapError(err, "ServerCert")
		return
	}
	// write "npkiRandomNum"
	err = en.Append(0xad, 0x6e, 0x70, 0x6b, 0x69, 0x52, 0x61, 0x6e, 0x64, 0x6f, 0x6d, 0x4e, 0x75, 0x6d)
	if err != nil {
		return
	}
	err = en.WriteBytes(z.NpkiRandomNum)
	if err != nil {
		err = msgp.WrapError(err, "NpkiRandomNum")
		return
	}
	return
}

// MarshalMsg implements msgp.Marshaler
func (z *VidMsgParams) MarshalMsg(b []byte) (o []byte, err error) {
	o = msgp.Require(b, z.Msgsize())
	// map header, size 3
	// string "input"
	o = append(o, 0x83, 0xa5, 0x69, 0x6e, 0x70, 0x75, 0x74)
	o = msgp.AppendString(o, z.Input)
	// string "serverCert"
	o = append(o, 0xaa, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x43, 0x65, 0x72, 0x74)
	o = msgp.AppendBytes(o, z.ServerCert)
	// string "npkiRandomNum"
	o = append(o, 0xad, 0x6e, 0x70, 0x6b, 0x69, 0x52, 0x61, 0x6e, 0x64, 0x6f, 0x6d, 0x4e, 0x75, 0x6d)
	o = msgp.AppendBytes(o, z.NpkiRandomNum)
	return
}

// UnmarshalMsg implements msgp.Unmarshaler
func (z *VidMsgParams) UnmarshalMsg(bts []byte) (o []byte, err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, bts, err = msgp.ReadMapHeaderBytes(bts)
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, bts, err = msgp.ReadMapKeyZC(bts)
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "input":
			z.Input, bts, err = msgp.ReadStringBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Input")
				return
			}
		case "serverCert":
			z.ServerCert, bts, err = msgp.ReadBytesBytes(bts, z.ServerCert)
			if err != nil {
				err = msgp.WrapError(err, "ServerCert")
				return
			}
		case "npkiRandomNum":
			z.NpkiRandomNum, bts, err = msgp.ReadBytesBytes(bts, z.NpkiRandomNum)
			if err != nil {
				err = msgp.WrapError(err, "NpkiRandomNum")
				return
			}
		default:
			bts, err = msgp.Skip(bts)
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	o = bts
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z *VidMsgParams) Msgsize() (s int) {
	s = 1 + 6 + msgp.StringPrefixSize + len(z.Input) + 11 + msgp.BytesPrefixSize + len(z.ServerCert) + 14 + msgp.BytesPrefixSize + len(z.NpkiRandomNum)
	return
}
